version: '3.4'

services:
  themane.web:
    image: themane.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - LOG_CONNECTION_STRING
      - DATASTORE_CONNECTION
      - DATASTORE_CONNECTION_TYPE
      - DATASTORE_CONNECTION_STRING

